plugins:
    - jekyll-minifier
jekyll-minifier:
    compress_css: false
    uglifier_args:
      harmony: true
sass:
    sass_dir: _sass
    style: compressed
cdn: "https://d2exodtkc8pqnq.cloudfront.net/"
